server:
  port: 9000

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: read:public_repo

  datasource:
    password: 123
    username: admin
    url: jdbc:postgresql://localhost:5432/admin?currentSchema=splitter

  flyway:
    create-schemas: true
    schemas: splitter
    url: jdbc:postgresql://localhost:5432/
    user: admin
    password: 123